### ISSUE TITLE
关于库 `pcaputil` 的一些小问题

### ISSUE THREAD

**Issue by Byxs20** [yaklang/yaklang#1043]
你好，我需要反馈一个小BUG：

使用库：`pcaputil`
流量包下载：[image.zip](https://github.com/yaklang/yaklang/files/14505369/image.zip)
问题：`image.pcapng` 这个流量是一个关于HTTP的，能正常读取HTTP的前4次的请求和返回，第五次就不太行了，是这个包的问题么，在WireShark中能正常的看到5个HTTP的请求包和返回包

报错内容截图：
![image](https://github.com/yaklang/yaklang/assets/64669718/e61e6504-0725-46c4-b2a2-846014a0cb9e)

详细报错的内容：[out.zip](https://github.com/yaklang/yaklang/files/14505411/out.zip)

我的代码如下：
```go
package main

import (
	"fmt"
	"log"
	"flag"
	"net/http"

	"github.com/yaklang/yaklang/common/pcapx/pcaputil"
)

var count = 1;
var fname = flag.String("r", "", "Filename to read from, overrides -i")

func main() {
	flag.Parse()

	if *fname == "" {
		fmt.Println("[!] 必须传入流量包的位置: xxx.exe -r <pcap_file>")
		return
	}
	
	if err := pcaputil.OpenPcapFile(*fname, 
		pcaputil.WithBPFFilter("http"), 
		pcaputil.WithHTTPFlow(handleHTTPFlow)); err != nil {
		log.Fatalln(err)
	}
}

func handleHTTPFlow(flow *pcaputil.TrafficFlow, req *http.Request, rsp *http.Response) {
	fmt.Printf("****** Req %d ******\n", count)
	fmt.Println(req.URL)
	fmt.Println(req.Body)
	fmt.Printf("****** Rsp %d ******\n", count)
	fmt.Println(rsp.Body)
	count ++
}

PS：是否能够添加一些功能
①是否能够添加HTTP的返回时候能够带上这个HTTP的 请求时间 和 返回时间
②还有在 `WireShark` 中左边看到的序号能否也能拿到，这样就可以对比起来分析流量，有问题的流量，看到序号后，就用 WireShark 去看，序号的由来应该就是经过多少个协议来的，具体实现的也不太清楚。
```

**Comment by VillanCh** [comment]
https://github.com/yaklang/yaklang/pull/982

大致记得在这个 PR 中修复的这个问题疑似这个反馈，师傅可以看一下你的包的代码的版本是不是最新的。

@OrangeWatermelon 师傅可以看一下这个 issue 的内容

**Comment by VillanCh** [comment]
WIP，大概近期版本会修复，流量基础设施的内容今年会是一个主要任务～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Byxs20 ***@***.***&gt;
发送时间: 2024年3月6日 18:59
收件人: yaklang/yaklang ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yaklang] 关于库 `pcaputil` 的一些小问题 (Issue #1043)





  
#982
 
大致记得在这个 PR 中修复的这个问题疑似这个反馈，师傅可以看一下你的包的代码的版本是不是最新的。
 
@OrangeWatermelon 师傅可以看一下这个 issue 的内容
  
image.png (view on web)
 
我的库是最新的，但是还是有问题，你可以复现一下我的代码看看
