### ISSUE TITLE
能导入第三方包吗

### ISSUE THREAD

**Issue by testnet0** [yaklang/yaklang#137]
像go一样import第三方的包，没有看到官方文档有相关的示例，是不支持导入第三方的包吗？

**Comment by VillanCh** [comment]
参考 common/yak/engine.go 中的操作，go 是静态类型语言，yaklang 是动态的

如果要使用别的 Go 的包，需要手动倒入到 YakVM 中

**Comment by WAY29** [comment]
如果你指的是import其他yak脚本，那样是可以的：https://yaklang.com/docs/yak-basic/modules
如果你指的是直接导入golang第三方包，很抱歉暂时没法实现
