### ISSUE TITLE
进制转换函数

### ISSUE THREAD

**Issue by nancunyitong** [yaklang/yaklang#1485]
请问有支持进制转换的函数么？整数之间的进制转换、2、8、10、16等

**Comment by WAY29** [comment]
我不太清楚你希望的输入和输出是什么：
假如你希望输入一个整数，得到对应进制的字符串，那么:
```yak
i = 10
sprintf("%b", i)  // 二进制
sprintf("%o", i)  // 八进制
sprintf("%x", i)  // 十六进制
```

假如你希望输入一个字符串，得到对应的整数，那么：
```yak
// 你可以直接输入字面量
0x10 // 16
0b1000 // 8
0100 // 64
```
值得注意的是，现在确实缺乏一个直接将字符串转换为对应进制整数的函数，预期会扩展`parseInt`函数，期望的结果如下：
```
parseInt("10", 16) // 16
```

**Comment by nancunyitong** [comment]
对的，就是想要一个这样的函数，期望的是parseInt("10", 10, 16)，可以指定输入的进制，转为指定进制
