### ISSUE TITLE
fatal error: concurrent map write

### ISSUE THREAD

**Issue by Jinone** [yaklang/yaklang#1545]
![image](https://github.com/user-attachments/assets/a69dc19f-67a6-438e-8b1d-bd7354ff244b)
看起来是并发写入map，多个goroutine访问 导致的问题
![image](https://github.com/user-attachments/assets/0dbf943a-34ca-4517-9109-b66ca47ddda1)

**Comment by WAY29** [comment]
师傅是执行了什么代码出现的问题？

**Comment by Jinone** [comment]
我在param.Fuzz(Payload).ExecFirst(HttpPoolConfigOption...)

使用了mutate.WithPoolOpt_Concurrent(2)设置
