### ISSUE TITLE
yak命令行函数synscan无法按照预期工作

### ISSUE THREAD

**Issue by Mada2aa** [yaklang/yaklang#1658]
无论是服务端还是本地都无法正常工作发现开放端口。
引擎版本：
Yak Language Build Info:
    Version: 1.3.4-rc5
    GoVersion: go version go1.20.14 darwin/arm64
    BuildTime: Fri Jul 26 18:45:56 2024 +0800
    GitHash: bdfec6212ed213ab3d6092cac6900a61e3c7206e
命令行：
(base) root@fancy-flags-2:~# yak synscan --target "baidu.com" --port "1-65535" -fp
[INFO] 2024-08-02 07:16:14 [route:75] fetching baidu.com 's address for 10s
[INFO] 2024-08-02 07:16:14 [scan_synscan:110] default config: 
    iface:eth0 src:23.106.130.51 gateway:23.106.128.1
[INFO] 2024-08-02 07:16:16 [scan_synscan:156] start create hyper scan center...
[INFO] 2024-08-02 07:16:17 [scan_synscan:163] preparing for result collectors
[INFO] 2024-08-02 07:16:17 [scan_synscan:200] start submit task and scan...
[INFO] 2024-08-02 07:16:17 [open_device:168] open iface lo success
[INFO] 2024-08-02 07:16:17 [capture_daemon:108] background iface: lo with (arp) or (tcp[tcpflags] & (tcp-syn) != 0) is start...
[INFO] 2024-08-02 07:16:17 [app:112] use arpx proto to fetch gateway's hw address: 44:aa:50:09:83:00
[INFO] 2024-08-02 07:16:17 [open_device:168] open iface eth0 success
[INFO] 2024-08-02 07:16:17 [capture_daemon:108] background iface: eth0 with (arp) or (tcp[tcpflags] & (tcp-syn) != 0) is start...
[INFO] 2024-08-02 07:16:19 [scan:245] start to wait all packets are sent
[INFO] 2024-08-02 07:16:20 [scan_synscan:229] finished submitting.
[INFO] 2024-08-02 07:16:20 [scan_synscan:271] waiting last packet (SYN) for 5 seconds
+------+------------+
| 主机 | 开放端口数 |
+------+------------+
+------+------------+

+------+------------+
| 端口 | 指纹（简） |
+------+------------+
+------+------------+

使用yak脚本正常工作：
target = "baidu.com"
ports = "1-65535"

syn, err := synscan.Scan(target, ports, synscan.concurrent(2000))
die(err)

serviceScanRet := servicescan.ScanFromSynResult(syn, servicescan.concurrent(200),servicescan.all())~
for ret = range serviceScanRet{
    dump(ret)
}

**Comment by VillanCh** [comment]
Rel: #1656

**Comment by Mada2aa** [comment]
已修复
