### ISSUE TITLE
[question]如何加载自定义的指纹库

### ISSUE THREAD

**Issue by Jecobo** [yaklang/yaklang#1786]
大佬，我阅读了yaklang关于指纹扫描教程，但是没找到关于加载自定义指纹规则方法
我在yak的安装目录也没有找到下面代码中的目录，还望指点如何使用yaklang加载自定义的指纹库
![1](https://github.com/user-attachments/assets/5966a719-2af9-494a-ac99-07f18c91312b)

**Comment by VillanCh** [comment]
加载自定义可以通过 “参数” 直接输入，但是 UI 目前没有关于这儿的输入位置，只能在编程的时候使用，详情可以找

![image](https://github.com/user-attachments/assets/53d33466-8a90-49db-9490-086c94251b2d)

这个接口的代码看一下

**Comment by Jecobo** [comment]
感谢大佬，我去看看！
