### ISSUE TITLE
启动mimt后无法访问，只能处于在127.0.0.1地址上的端口监听

### ISSUE THREAD

**Issue by NeoACCG** [yaklang/yaklang#1953]
### 问题复现
当正常启动yak服务端后，并按照正常方式使用yakit时，一旦启动mimt并指定远程服务器，而处于远程服务器的yak却只监听本地127.0.0.1对应的端口，而不是以0.0.0.0进行监听
![image](https://github.com/user-attachments/assets/4f389871-2151-4204-9366-f71670963b73)

从而导致yakit无法连接到远程服务器的代理

![image](https://github.com/user-attachments/assets/29d4f4de-2a7b-477e-8e18-58ec707fdec6)

**Comment by WAY29** [comment]
请截图你启动mitm时的界面

**Comment by WAY29** [comment]
stale
