### ISSUE TITLE
spacengine.FofaQuery 返回值出错

### ISSUE THREAD

**Issue by shihao-shen** [yaklang/yaklang#297]
spacengine.FofaQuery返回的对象中，HtmlTitle标题变成了端口号，Addr少了端口
![2023-08-11_11-24-44](https://github.com/yaklang/yaklang/assets/59755487/fb37c923-7d26-484d-8b3f-45cf6ad56287)

**Comment by WAY29** [comment]
师傅能给个复现方式吗?

**Comment by WAY29** [comment]
我刚刚测试了一下,应该是fofa私自修改了响应结果位置导致出现了错位(由于fofa的返回结果是个Array而不是Object)

**Comment by WAY29** [comment]
will fixed by [this pull request](https://github.com/yaklang/yaklang/pull/298)
