### ISSUE TITLE
What is `pbbp2` from HTTP header?

### ISSUE THREAD

**Issue by ringsaturn** [yaklang/yaklang#332]
I’m reading codes and found a header I don’t know

```
Sec-WebSocket-Protocol: pbbp2
```

https://github.com/yaklang/yaklang/blob/4fad46145d5fddd892aa60bebdc4c61d1c38f2b2/common/vulinbox/service_wsagent.go#L111

Any doc/RFC for this Header value?

**Comment by WAY29** [comment]
just search, and you can find this [RFC](https://datatracker.ietf.org/doc/html/rfc6455#section-11.3.4)

**Comment by ringsaturn** [comment]
What does pbpb2 mean?

**Comment by WAY29** [comment]
> 

This is just a protocol agreed upon between the client and server, and the specific implementation depends on the client and server.

This data packet was only copied and modified by us from the internet. If the server and client do not implement this sub protocol, it has no effect.
