### ISSUE TITLE
建议增加 arm 架构的版本编译文件

### ISSUE THREAD

**Issue by allinu** [yaklang/yaklang#409]
不知道提升大不大，还希望作者解答，如果有性能上的提升，那再好不过了 🥺

**Comment by VillanCh** [comment]
增加确实也没有啥问题，现在代码应该没有特别多设计对不同架构的设计，大部分用户需要 linux 版本都可自行编译～

欢迎师傅有空协助我们修改 Github Actions 的分发脚本增加相应配置

`.github/workflows/...`

**Comment by WAY29** [comment]
师傅指的是linux的arm64版本还是mac的？

**Comment by allinu** [comment]
@WAY29 我用的是Mac m1但是在不增加你们开发成本的情况下，覆盖越多越好嘛

**Comment by VillanCh** [comment]
#414

**Comment by WAY29** [comment]
遇到了新的问题，github的ci没有arm64架构的runner

**Comment by allinu** [comment]
@WAY29 嘶，我对这个CI书写方式不太熟悉，目前更改的状况是参考其他项目和官方文档以及自己的一些推测，macos-arm64我不知道有没有，但是ARM64应该是有的，我提供一些链接，可以看一下，我不知道怎么添加修改。
- https://docs.github.com/zh/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow#using-default-labels-to-route-jobs
- https://docs.github.com/zh/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners
- https://docs.github.com/zh/actions/hosting-your-own-runners/managing-self-hosted-runners/configuring-the-self-hosted-runner-application-as-a-service
- https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

**Comment by VillanCh** [comment]
经过各种测试和实践，实际推荐用独立的物理机 mac arm64 打包编译是最合适的，目前 github actions 确实不会提供 arm64 mac 架构的 ci runner
