### ISSUE TITLE
strings.TrimLeft，Trim函数bug

### ISSUE THREAD

**Issue by Liehu** [yaklang/yaklang#557]
URL = "https://domain/static/js/app.1696919709975.js"
sub_path = str.TrimLeft(URL,`https://domain`)
println(sub_path)
输出为：atic/js/app.1696919709975.js
正确输出应该是static/js/app.1696919709975.js
无论开头多少个s,t都会被过滤
![image](https://github.com/yaklang/yaklang/assets/4949212/3e967e6d-0a71-452c-8adc-b3bdf84fa0c4)

**Comment by WAY29** [comment]
师傅如果学过编程的话应该知道，TrimLeft的作用是将字符串左侧所有包含cutset字符串中的字符都去掉，所以师傅可能是用错函数了，考虑使用str.TrimPrefix函数
