### ISSUE TITLE
如何关闭[INFO]等信息？

### ISSUE THREAD

**Issue by redcrossth2049** [yaklang/yaklang#567]
![image](https://github.com/yaklang/yaklang/assets/145326817/76fcdc05-ad04-492d-b3e5-05caa8a99f09)
调用syncscan时，一直出现这些信息，请问如何设置，不显示[INFO][ERRO]等信息？

**Comment by VillanCh** [comment]
在代码开头使用 `loglevel("error")` 可以消除 INFO

**Comment by WAY29** [comment]
师傅也可以使用`lodsicard()`来在yak中丢弃所有的log信息
