### ISSUE TITLE
调用synscan.Scan()出现“no loopback iface found”错误

### ISSUE THREAD

**Issue by redcrossth2049** [yaklang/yaklang#568]
调用synscan.Scan()时出现如下的错误，求问应该如何解决？
YakVM Panic: create hyper scan center failed: create syn scanner failed: no loopback iface found

**Comment by redcrossth2049** [comment]
同时还有如下错误：
YakVM Panic: create hyper scan center failed: create syn scanner failed: convert iface name failed: Ethernet0

**Comment by redcrossth2049** [comment]
是否是因为我开了多线程同时调用synscan.Scan()的原因？如果是的话，应该如何多线程调用synscan？

**Comment by WAY29** [comment]
师傅能提供更多执行环境的信息吗？比如是使用什么系统？是否使用虚拟机？以及网卡信息（`ipconfig`或`ifconfig`）

**Comment by redcrossth2049** [comment]
我的环境是VMware Win11的虚拟机，我发现确实是多线程同时调用synscan.Scan()的原因，改为单线程后没有出现“
no loopback iface found”和“convert iface name failed: Ethernet0”错误。
现在我想调用synscan.concurrent()设置synscan的并发，结果出现如下错误：
源码：
`
println("case 2", threads)
servicescan.concurrent(threads)
res, err := synscan.Scan(target,ports)
 die(err)
`
错误：
`
case 2 10
[WARN] 2023-10-27 11:25:09 [vm_panic:88] BUG: handling panic code review failed: Panic Stack:
YakVM Panic: native func `synscan.Scan` calling failed: auto convert failed, cannot convert fp.ConfigOption(passed) to []tools.scanOpt(need)

exec yakc with code failed: Panic Stack:
function: scan
--> 27
__yak_main__
--> 50 (target,scan_ports,scan_type,threads)

YakVM Panic: native func `synscan.Scan` calling failed: auto convert failed, cannot convert fp.ConfigOption(passed) to []tools.scanOpt(need)
`

将源码改为`res, err := synscan.Scan(target,ports,servicescan.concurrent(threads))`后亦出现相同错误。
求问：synscan如何设置高并发？

**Comment by Go0p** [comment]
应当使用 `synscan.concurrent`

例如 ：
```
synResults, err := synscan.Scan(target, ports, synscan.initHostFilter(hosts), synscan.initPortFilter(ports),
        synscan.excludeHosts(excludeHosts), synscan.excludePorts(excludePorts),
        synscan.submitTaskCallback(func(i){ addSynPacketCounter() }),
        synscan.concurrent(synConcurrent),
    )
die(err)
```


有关 synscan.Scan 的参数可以参考官网 api 文档

https://yaklang.com/docs/api/synscan/#concurrent
