### ISSUE TITLE
请问一下yaklang与golang的关系

### ISSUE THREAD

**Issue by cutalk** [yaklang/yaklang#57]
如标题

**Comment by VillanCh** [comment]
Yaklang的YakVM是Golang实现的，因此Golang的库可以直接生成YakVM支持的库





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tj ***@***.***&gt;
发送时间: 2023年5月27日 10:48
收件人: yaklang/yaklang ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yaklang] 请问一下yaklang与golang的关系 (Issue #57)





 
如标题

**Comment by cutalk** [comment]
> 

看了下，语法有点像，又有点js的感觉。能用golang库会方便很多  ^_^

**Comment by VillanCh** [comment]
师傅可以仓库内搜索YaklangLexer.g4和YaklangParser.g4可以看到完整的语法生成式



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tj ***@***.***&gt;
发送时间: 2023年5月27日 10:58
收件人: yaklang/yaklang ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yaklang] 请问一下yaklang与golang的关系 (Issue #57)





   
看了下，语法有点像，又有点js的感觉。能用golang库会方便很多  ^_^
