### ISSUE TITLE
混合开发

### ISSUE THREAD

**Issue by cuiyimeng** [yaklang/yaklang#643]
请问yaklang是否可以和go混合开发？有这方面的例子或教程吗

**Comment by VillanCh** [comment]
整个仓库几乎都是使用案例，大量的安全相关的功能都是 yak 和 go 的混合编码

可以把 yaklang 这个项目像“库”一样导入你的 golang 项目，直接 `yak.Execute(...)` 就可以执行一段 yak 代码，如果需要更多人机交互，可以直接查看本项目中的其他代码，搜索关键词 yak ScriptEngine yakvm 等

**Comment by WAY29** [comment]
另外请注意该仓库的LICENSE：
```
本仓库代码版本使用 AGPL 开源协议，这是一个严格的开源协议，且具有传染性，如果您使用了本仓库的代码，那么您的代码也必须开源。
```

**Comment by cuiyimeng** [comment]
@VillanCh 非常感谢您的回复，我去了解一下，很抱歉回复的不及时

**Comment by cuiyimeng** [comment]
@WAY29 好的，了解
