### ISSUE TITLE
mac使用sycnscan扫描内网段，如何指定网卡，默认获取的网卡无法扫描，也无法获取到网关

### ISSUE THREAD

**Issue by b1cat** [yaklang/yaklang#872]
mac使用sycnscan扫描内网段，如何指定网卡，默认获取的网卡无法扫描，也无法获取到网关

<img width="1225" alt="image" src="https://github.com/yaklang/yaklang/assets/30470078/b7ac019c-4033-4cd9-98fc-f31db0409f26">

正常应该使用en0这个网卡

<img width="639" alt="image" src="https://github.com/yaklang/yaklang/assets/30470078/3ca8f910-486a-443d-845e-94534bf58bf1">

**Comment by b1cat** [comment]
test.yak

<img width="757" alt="image" src="https://github.com/yaklang/yaklang/assets/30470078/a4223c50-ea51-41bb-9cec-30ea96ac6a27">

**Comment by VillanCh** [comment]
在新的版本中，synscan 应该是新增了可以手动指定网卡的功能

@Go0p

**Comment by VillanCh** [comment]
#903
