### ISSUE TITLE
[讨论] 是否有可能嵌入到其他工具中？

### ISSUE THREAD

**Issue by M09Ic** [yaklang/yaklang#967]
在调研是否存在一个足够方便的script语言能用来支撑插件系统（非yakit插件）时想到yaklang。但过了一遍文档，yaklang似乎是为了yakit设计的。 

例如在ASM或者C2工具中， 是否可能将yaklang嵌入其中， 作为插件系统的底层驱动。就像是cobalt strike的aggressor script(sleep 语言）那样。 使用yaklang给非yakit工具编写插件。 我看到yakit是这样做的， 但似乎没找到独立使用yaklang的文档。

渗透工具箱railgun中的插件系统实现使用了yaegi, https://xz.aliyun.com/t/11318.

**Comment by VillanCh** [comment]
Yaklang的Golang SDK可以独立使用，其实Yaklang也已经有很多独立使用和集成案例，只是因为没有官方指导，也没有相关文章专门讲这个事，大部分这种用户在私下使用和集成


实际使用中yaklang的语法和库的制作方面，可用性和完整程度应该已经远强于市面上让绝大多数脚本容器。


但是引擎体积目前比较大，如果有需要独立集成，需要手动裁剪内置库

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: M09Ic ***@***.***&gt;
发送时间: 2024年2月13日 04:39
收件人: yaklang/yaklang ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yaklang] [讨论] 是否有可能嵌入到其他工具中？ (Issue #967)





 
在调研是否存在一个足够方便的script语言能用来支撑插件系统（非yakit插件）时想到yaklang。但过了一遍文档，yaklang似乎是为了yakit设计的。
 
例如在ASM或者C2工具中， 是否可能将yaklang嵌入其中， 作为插件系统的底层驱动。就像是cobalt strike的aggressor script(sleep 语言）那样。 使用yaklang给非yakit工具编写插件。 我看到yakit是这样做的， 但似乎没找到独立使用yaklang的文档。
 
渗透工具箱railgun中的插件系统实现使用了yaegi, https://xz.aliyun.com/t/11318.

**Comment by M09Ic** [comment]
感谢你的回复。我搜索了下github，似乎没有找到这样的案例，方便提供几个ref不，麻烦了

**Comment by VillanCh** [comment]
Go get yaklang的包，然后Import yaklang.NewEngine就可以直接用编程API了，或者直接看 yakit 是如何使用 yaklang 的编程接口代码的，在仓库 grpc_开头的代码文件中


也可以直接使用 grpc 接口完成





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: M09Ic ***@***.***&gt;
发送时间: 2024年2月13日 12:11
收件人: yaklang/yaklang ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yaklang] [讨论] 是否有可能嵌入到其他工具中？ (Issue #967)





 
感谢你的回复。我搜索了下github，似乎没有找到这样的案例，方便提供几个ref不，麻烦了

**Comment by wlingze** [comment]
yaklang 语言部分执行接口在[这个文件](https://github.com/yaklang/yaklang/blob/main/common/yak/script_engine.go)内, 
* 直接代码执行参考 [`Execute`函数](https://github.com/yaklang/yaklang/blob/f8f99a323077760711ab340dfc3aa748a0387f03/common/yak/script_engine.go#L669)
* 相关依赖库的注入参考 [`initYaklangLib`函数](https://github.com/yaklang/yaklang/blob/f8f99a323077760711ab340dfc3aa748a0387f03/common/yak/script_engine.go#L84)
你可以从这两个接口，向下继续了解engine是如何运行，拆解适合的借口出来，或向上引用查看项目代码或测试样例中是如何使用的。
